// Assemble the self-contained AudioWorklet processor.
//
// An AudioWorklet module must not rely on nested `import`s — browser support
// is inconsistent and the failure mode is silent (the processor simply never
// registers). So we prepend the wasm-bindgen glue to the processor source
// and emit a single import-free file. Run after every `wasm-pack build`.

import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, '..');

const wasmDir = resolve(webRoot, 'public/microtube-worklet/wasm');
const gluePath = resolve(wasmDir, 'microtube_core.js');
const srcPath = resolve(webRoot, 'worklet/processor.src.js');
const outPath = resolve(webRoot, 'public/microtube-worklet/processor.js');

const glue = readFileSync(gluePath, 'utf8');
const processor = readFileSync(srcPath, 'utf8');

const banner =
  '// GENERATED by scripts/build-worklet.mjs — do not edit.\n' +
  '// = TextDecoder/TextEncoder shim + wasm-bindgen glue + processor.src.js,\n' +
  '// concatenated so the AudioWorklet module has no nested imports.\n\n';

// `AudioWorkletGlobalScope` exposes neither `TextDecoder` nor `TextEncoder`,
// yet the wasm-bindgen glue constructs a `TextDecoder` at module top level.
// Without this shim the glue throws on load and `registerProcessor` never
// runs — the engine API itself passes no strings, so a compact UTF-8
// polyfill is plenty.
const polyfill = `// --- AudioWorklet text-codec shim -----------------------------------------
if (typeof globalThis.TextDecoder === 'undefined') {
  globalThis.TextDecoder = class {
    constructor() {}
    decode(input) {
      if (!input) return '';
      const view = input instanceof Uint8Array
        ? input
        : new Uint8Array(input.buffer ?? input, input.byteOffset ?? 0, input.byteLength);
      let binary = '';
      for (let i = 0; i < view.length; i++) binary += String.fromCharCode(view[i]);
      return decodeURIComponent(escape(binary));
    }
  };
}
if (typeof globalThis.TextEncoder === 'undefined') {
  globalThis.TextEncoder = class {
    encode(str) {
      const binary = unescape(encodeURIComponent(str ?? ''));
      const out = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
      return out;
    }
    encodeInto(str, dest) {
      const enc = this.encode(str);
      const n = Math.min(enc.length, dest.length);
      dest.set(enc.subarray(0, n));
      return { read: str.length, written: n };
    }
  };
}
// --------------------------------------------------------------------------

`;

writeFileSync(outPath, banner + polyfill + glue + '\n\n' + processor);
console.log(`[build-worklet] wrote ${outPath}`);

// The glue is now inlined into processor.js; at runtime only the raw
// `.wasm` binary is fetched. Prune the rest of the wasm-pack output so it
// is not needlessly published as static assets.
for (const stale of [
  'microtube_core.js',
  'microtube_core.d.ts',
  'microtube_core_bg.wasm.d.ts',
  'package.json',
  '.gitignore',
  'README.md',
  'LICENSE',
]) {
  const p = resolve(wasmDir, stale);
  if (existsSync(p)) rmSync(p);
}
console.log('[build-worklet] pruned wasm/ to microtube_core_bg.wasm');
